server:
  port: 8981
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://D:/code/java/spring-cloud-config-centre #https://github.com/zhaoyunxing92/spring-cloud-config-centre.git
          search-paths: respo
      label: master
#logging:
#  level:
#      com: debug
#      org: debug
