spring:
  application:
    name: ribbon
server:
  port: 8764
  servlet:
    context-path: /ribbon
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
