spring:
  application:
    name: eureka-provider
server:
  port: 8700
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
#    hostname: localhost
    lease-expiration-duration-in-seconds: 30 #设置租期到期时间 （默认90秒）
    lease-renewal-interval-in-seconds: 10   #租期更新时间间隔（默认30秒）


