server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false  #禁止从获取eureka注册信息
    register-with-eureka: false # 是否注册到eureka
    serviceUrl:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-replicated-request-compression: false #关闭自我保护
#    eviction-interval-timer-in-ms: 30000 # 清理时间
spring:
  application:
    name: eureka-server
    
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

#开启安全验证
#spring:
#  security:
#    user:
#      name: sunny
#      password: sunny
#    basic:
#      enabled: true
#  application:
#    name: eureka-server  # 服务名称
# logging:
#   level:
#     root: debug
#     com:
#      spring: debug
